packages:
  - name: default
    functions:
      - name: auth-api
        main: index.js
        runtime: nodejs:18
        web: true
        limits:
          timeout: 10000
          memory: 256
      - name: paypal-webhook
        main: index.js
        runtime: nodejs:18
        web: true
        limits:
          timeout: 10000
          memory: 256
      - name: send-email
        main: index.js
        runtime: nodejs:18
        web: true
        limits:
          timeout: 10000
          memory: 256
